/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bowling;

/**
 *
 * @author LC
 */
public class Game extends javax.swing.JFrame {

    private Player player1;
    private Player player2;
    short score1, score2;
    byte intento = 1;
    byte contador = 1;
    byte pinos = 10;
    
    public Game(Player player1, Player player2) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.player1= player1;
        this.player2=player2;
        llenarNombres();//Metodo para llenar los nombres
        btnLanza2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre1 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JLabel();
        derribos = new javax.swing.JLabel();
        btnLanza1 = new javax.swing.JButton();
        btnLanza2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombre1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombre1.setText("Nombre 1");

        nombre2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombre2.setText("Nombre 2");

        derribos.setText("jLabel1");

        btnLanza1.setText("¡Lanzar Player 1!");
        btnLanza1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanza1ActionPerformed(evt);
            }
        });

        btnLanza2.setText("¡Lanzar Player 2!");
        btnLanza2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanza2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(derribos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLanza1)
                        .addGap(70, 70, 70)
                        .addComponent(btnLanza2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(nombre2)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre1)
                    .addComponent(nombre2))
                .addGap(76, 76, 76)
                .addComponent(derribos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLanza1)
                    .addComponent(btnLanza2))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanza1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanza1ActionPerformed

        if(contador<21)
        {
            byte lanzamiento = Random.Azar(pinos);
        pinos = (byte) (pinos - lanzamiento);
        System.out.println(lanzamiento);
        intento++;
        score1= (short)(score1+lanzamiento);
        player1.setScore((short)(player1.getScore() + score1));
        contador++;
        if(lanzamiento == 10)
        {
            derribos.setText("Strike!");
        }
        derribos.setText("Derribaste "+lanzamiento+" pinos");
        if(pinos == 0 && intento == 2)
        {
            btnLanza1.setEnabled(false);
            btnLanza2.setEnabled(true);
            pinos=10;
            intento=1;
        }
        if(intento==3) 
        {
            btnLanza1.setEnabled(false);
            btnLanza2.setEnabled(true);
            pinos=10;
            intento=1;
        }
        }
        
        btnLanza1.setEnabled(false);
        btnLanza2.setEnabled(false);
    }//GEN-LAST:event_btnLanza1ActionPerformed

    private void btnLanza2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanza2ActionPerformed
        if(contador<21){
            byte lanzamiento = Random.Azar(pinos);
        pinos = (byte) (pinos - lanzamiento);
        System.out.println(lanzamiento);
        intento++;
        score1= (short)(score1+lanzamiento);
        player1.setScore((short)(player1.getScore() + score1));
        contador++;
        if(lanzamiento == 10)
        {
            derribos.setText("Strike!");
        }
        derribos.setText("Derribaste "+lanzamiento+" pinos");
        if(pinos == 0 && intento == 2)
        {
            btnLanza1.setEnabled(true);
            btnLanza2.setEnabled(false);
            pinos=10;
            intento=1;
        }
        if(intento==3) 
        {
            btnLanza1.setEnabled(true);
            btnLanza2.setEnabled(false);
            pinos=10;
            intento=1;
        }
        }
        
            btnLanza1.setEnabled(false);
            btnLanza2.setEnabled(false);
    }//GEN-LAST:event_btnLanza2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLanza1;
    private javax.swing.JButton btnLanza2;
    private javax.swing.JLabel derribos;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    // End of variables declaration//GEN-END:variables

    private void llenarNombres() {
        //Obtenemos ambos nombres de los jugadores y los ponemos en los 
        nombre1.setText(player1.getNombre());
        nombre2.setText(player2.getNombre());
    }
}
