/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bowling;


import tabla.Records;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import com.google.gson.Gson;
import java.awt.List;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javax.swing.RowSorter;
import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import tabla.Record;



/**
 *
 * @author Edson
 */
public class Puntajes extends javax.swing.JFrame {

    /**
     * Creates new form Puntajes
     */
    
    public Puntajes() {
        initComponents();
        this.setLocationRelativeTo(null);
        llenarTabla();//funcion temporal simular el llenado de  la tabla
        CargaDatos();//funcion para cargar los maximos scores del juego
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnVolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnVolver)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Main main = new Main();//Se instancia la ventana para ser utilizada
        main.setVisible(true);//Ponemos visible la ventana
        this.setVisible(false);//Dejamos invible la ventana anterior
    }//GEN-LAST:event_btnVolverActionPerformed

    private void CargaDatos() {
     
       Gson gson = new Gson();
       try {
                //Se lee el archivo json que contiene los records
		BufferedReader br = new BufferedReader(new FileReader("score.json"));

		//El archivo json se combierte en un objeto
		Records records = gson.fromJson(br, Records.class);
                if(records.getRecords().isEmpty()){
                    text.setText("El sistema no regristra ningun record, juega para ser el primero");
                    
                }
                
                else{
                    Collections.sort(records.getRecords(), new Comparator() {
                        //Sobre-escribimos el motodo compare para indicar cual es la variable que queremos comparar para ordenar la lista
                        @Override
                        public int compare(Object o1, Object o2) {
                            
                            return new Short(((Record)o2).getPlayer().getScore()).compareTo(((Record)o1).getPlayer().getScore());
                        }
                    });
                    DefaultTableModel model;
                    model = new DefaultTableModel(); 
                    
                    model.addColumn("Lugar");
                    model.addColumn("Nombre");
                    model.addColumn("Puntaje");
                    model.addColumn("Fecha");
                    
                    for (int i = 0; i < records.getRecords().size(); i++) {
                        model.addRow(new Object[]{"N°"+(i+1),records.getRecords().get(i).getPlayer().getNombre(), Short.toString(records.getRecords().get(i).getPlayer().getScore()), records.getRecords().get(i).getFecha().toString()});
                    }
                    
                    
                    jTable2.setModel(model);
                    jTable2.setEnabled(false);
                    text.setText("Estos son los puntajes encontrados en el sistema");

                }
                
                
		

	} catch (IOException e) {
            CrearArchivo();//funcion para crear el archivo de scores en caso que no exista
            text.setText("El sistema no regristra ningun record, juega para ser el primero");
            
	}
       catch (Exception e) {
            text.setText("A ocurrido un error al cargar los scores registrados en el sistema");
	}
    }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables

    private void CrearArchivo() {
        Gson gson = new Gson();
        Records records= new Records();
	String json = gson.toJson(records);

	try {
		//se escribe el archivo json vacio con la estructura correspondiente "score.json"
		FileWriter writer = new FileWriter("score.json");
		writer.write(json);
		writer.close();

	} catch (IOException e) {
		text.setText("Ha ocurrido un error de escritura al crear el archivo");
	}

    }

    private void llenarTabla() {
        Records records= new Records();
        records.ingresar(new Record(new Player("juan",(short)21), new Date()));
        records.ingresar(new Record(new Player("Pedro",(short)90), new Date()));
        records.ingresar(new Record(new Player("Diego",(short)65), new Date()));
        records.ingresar(new Record(new Player("Maria",(short)20), new Date()));
        records.ingresar(new Record(new Player("Rocio",(short)140), new Date()));
        records.ingresar(new Record(new Player("Masaña",(short)0), new Date()));
        Gson gson = new Gson();
        // convert java object to JSON format,
        // and returned as JSON formatted string
        String json = gson.toJson(records);
          try {
                    //write converted json data to a file named "file.json"
                    FileWriter writer = new FileWriter("score.json");
                    writer.write(json);
                    writer.close();

            } catch (IOException e) {
                    e.printStackTrace();
            }
        }

   
    
}
